---
title: "Assignment Due Dates"
---


Below are the due dates for the assignments, as well as links to each assignment. The due dates may change at the instructor's discretion. Any revised due dates will be announced in class and posted to the website. 

<br />

<table class="table">

<thead>
<tr>
<th style="width:50%;">Assignment</th>
<th style="width:15%;">Due Date (T/R)</th>
<th style="width:15%;">Due Date (M/W)</th>
<th style="width:10%;text-align:center">QMD</th>
<th style="width:10%;text-align:center">HTML</th>
</tr>
</thead>

<tbody>

<tr>
<td>Assignment \#1: *Introduction to Quarto*</td>
<!-- <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[The due date for this assignment is flexible]*</span> -->
<td>Feb. 09</td>
<td>Feb. 13</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/assignments/assignment-01-introduction-to-quarto.qmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="font-size: 20px;"></span>](assignments/assignment-01-introduction-to-quarto.html)
</td>
</tr>


<tr>
<td>Assignment \#2: *Polynomial Effects*</td>
<!-- <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[The due date for Question 11 is flexible]*</span> -->
<td>Feb. 21</td>
<td>Feb. 22</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/assignments/assignment-02-polynomial-effects.qmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="font-size: 20px;"></span>](assignments/assignment-02-polynomial-effects.html)
</td>
</tr>


<tr>
<td>Assignment \#3: *Evidence and Model Selection*</td>
<!-- <br /><span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Updated: 02-08-2022]*</span> -->
<td>Mar. 02</td>
<td>Mar. 13</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/assignments/assignment-03-evidence-and-model-selection.qmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="font-size: 20px;"></span>](assignments/assignment-03-evidence-and-model-selection.html)
</td>
</tr>


<tr>
<td>Assignment \#4: *Logarithmic Transformations*</td>
<td>Mar. 23</td>
<td>Mar. 27</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/assignments/assignment-04-logarithmic-transformations.qmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="font-size: 20px;"></span>](assignments/assignment-04-logarithmic-transformations.html)
</td>
</tr>


<tr>
<td>Assignment \#5: *Logistic Regression*</td>
<!-- <br /><span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Updated: 03-24-2022]*</span> -->
<td>Apr. 11</td>
<td>Apr. 10</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/assignments/assignment-05-logistic-regression.qmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="font-size: 20px;"></span>](assignments/assignment-05-logistic-regression.html)
</td>
</tr>


<tr>
<td>Assignment \#6: *LMER: Unconditional Longitudinal Models*</td>
<td>Apr. 25</td>
<td>Apr. 24</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/assignments/assignment-06-lmer-unconditional-longitudinal-models.qmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="font-size: 20px;"></span>](assignments/assignment-06-lmer-unconditional-longitudinal-models.html)
</td>
</tr>


<tr>
<td>Assignment \#7: OPTIONAL --- *LMER: More Longitudinal Models*</td>
<td>May 06</td>
<td>May 06</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/assignments/assignment-07-lmer-more-longitudinal-models.qmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="font-size: 20px;"></span>](assignments/assignment-07-longitudinal-analysis-ii.html)
</td>
</tr>



</tbody>
</table>




