---
title: "Introduction to Quarto"
format:
  html:
   css: "../assets/sticky-notes.css"
date: "`r format(Sys.Date(), '%B %d %Y')`"
---

<!-- ## What is Quarto? -->

<!-- Quarto® is an open-source scientific and technical publishing system built on Pandoc. For us, it allows us to embed R syntax directly in a text document. Using Quarto is one of the first steps to making your research more reproducible. By integrating your R syntax and your text into a single document, it also improves your analytical workflow. -->


<!-- ## Similar to RMarkdown...But Better -->

<!-- For those of you familiar with RMarkdown, Quarto® is a multi-language, next generation version of R Markdown from RStudio, with many new new features and capabilities. Like R Markdown, Quarto® uses Knitr to execute R code, and is therefore able to render most existing Rmd files without modification. -->


## Install Quarto

1.  Head over to <https://quarto.org/> and click on the big, blue "Get Started" button. Then follow the instructions to install Quarto.
2.  Open RStudio. (Note if RStudio was open when you installed Quarto, quit and re-open it.)

At this point in RStudio, if you go to `File > New File...` you should see options to choose `Quarto Document` and `Quarto Presentation`.

<br />

## Help and Tutorials

There are several [guides and tutorials](https://quarto.org/docs/guide/) available on the Quarto website. These include:

-   Creating basic content (e.g., figures, tables, diagrams, footnotes, citations)
-   Including computation/syntax
-   Generating output in different formats (e.g., HTML, PDF, MS Word)
-   Creating slides and presentations (These notes are a Quarto presentation!)
-   Building websites
-   Building books
-   Creating interactive dashboards

<br />


## Create Your First Quarto Document

Click the [Tutorial: Hello Quarto](https://quarto.org/docs/get-started/hello/rstudio.html) link on the left-side of the "Getting Started" page. Make sure that the RStudio tool is selected at the top of the tutorial.

<br />

Work through this tutorial. This will introduce you to some of the basic concepts of creating and rendering a Quarto document.

<br />


## Learning How to Integrate R Code

Also work through the [Tutorial: Computations](https://quarto.org/docs/get-started/computations/rstudio.html). Again, before starting, ensure that the RStudio tool is selected at the top of the tutorial.


<br />


## Learn More

Check out the Welcome to Quarto Workshop. This is a 2 1/2 hour workshop introducing people to Quarto.

- [Welcome to Quarto Workshop! (YouTube Video)](https://www.youtube.com/watch?v=yvi5uXQMvu4)


If you are familiar with RMarkdown and want to learn how to switch over to Quarto, here is a nice 30 minute talk by Mine Çetinkaya-Rundel that helps you do that.

- [2022 Toronto Workshop on Reproducibility - Mine Çetinkaya-Rundel (YouTube Video)](https://www.youtube.com/watch?v=6p4vOKS6Xls)







